version: "3"
services:
  oor:
    image: jortizpa/oor
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      0rloc:
          ipv4_address: <ip>
      1eids:
          ipv4_address: <ip>
    environment:
      - IPV4EIDPREFFIX="<network>\/<mask>"
      - IPV6EIDPREFFIX="<network>\/<mask>"
      - DEBUG="3"
      - OPMODE="xTR"
      - IPMAPRESOLVER=<IP of the MapResolver>
      - IPMAPSERVER=<IP of the MapServer>
      - KEYMAPSERVER=<String>
      - IPPROXYETRV4=<IP of the Proxy ETR IPv4>
      - IPPROXYETRV6=<IP of the Proxy ETR IPv6>
      - IPV4EIDPREFFIX=<EID IPv4 Preffix>
      - IPV6EIDPREFFIX=<EID IPv6 Preffix>
    restart: on-failure
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30 <your_stack_container_name>

networks:
  1eids:
    driver: macvlan
    ipam:
      driver: default
      config:
      - subnet: <EID IPv4 Preffix>
    driver_opts:
      parent: <linux host interface>
      macvlan_mode: bridge
  0rloc:
    driver: macvlan
    ipam:
      driver: default
      config:
      - subnet: <RLOC Subnet>
    driver_opts:
      parent: <linux host interface>
      macvlan_mode: bridge
