version: "2.3"
services:
  msmr:
    container_name: oor-msmr
    image: openoverlayrouter/oor:testing
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      0rloc:
          ipv4_address: 10.0.0.2
    volumes:
      - type: bind
        source: "./oor.msmr.conf"
        target: "/oor/oor.conf"
    restart: on-failure

  xtr1:
    container_name: oor-xtr1
    image: openoverlayrouter/oor:testing
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      0rloc:
          ipv4_address: 10.0.0.3
          ipv6_address: fd00::3
      1eid:
          ipv4_address: 192.168.1.2
          ipv6_address: fd00:1::2
    volumes:
      - type: bind
        source: "./oor.xtr1.conf"
        target: "/oor/oor.conf"
    restart: on-failure

  xtr2:
    container_name: oor-xtr2
    image: openoverlayrouter/oor:testing
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0  
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      0rloc:
          ipv4_address: 10.0.0.4
          ipv6_address: fd00::4
      2eid: 
          ipv4_address: 192.168.2.2
          ipv6_address: fd00:2::2
    volumes:
      - type: bind
        source: "./oor.xtr2.conf"
        target: "/oor/oor.conf"
    restart: on-failure

  
  client1:
    container_name: client1
    image: busybox
    command: top
    networks:
      1eid:
          ipv4_address: 192.168.1.3
          ipv6_address: fd00:1::3

  client2:
    container_name: client2
    image: busybox
    command: top
    networks:
      2eid:
          ipv4_address: 192.168.2.3
          ipv6_address: fd00:2::3
          
          
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30 oor-msmr oor-xtr1 oor-xtr2       

networks:
  0rloc:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
      - subnet: fd00::/64 

  1eid:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24
      - subnet: fd00:1::/64 

  2eid:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 192.168.2.0/24
      - subnet: fd00:2::/64
